SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/AbstractDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import java.io.Serializable;

/**
 *
 * @author mickapa1
 */
public class AbstractDto implements Serializable{
    protected Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AbstractDto other = (AbstractDto) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }
    
    
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/AdminDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

/**
 *
 * @author Jirka
 */
public class AdminDto extends UserDto{

    
    public AdminDto() {
    }

    public AdminDto(Long id, String username) {
        super(id, username);
    }
    
    

}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/AdvisoryBoardMemberDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

/**
 *
 * @author Jirka
 */
public class AdvisoryBoardMemberDto extends PersonAbstractDto {

    public AdvisoryBoardMemberDto() {
    }
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/AnnotationDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

/**
 *
 *
 * @author Jirka
 */
public class AnnotationDto extends AbstractDto {

    String pathOfFile;
    String annotation;
    Long articleId;
    Long authorOfAnnotationId;

    public AnnotationDto() {
    }

    public AnnotationDto(Long id, String pathOfFile, String annotation, Long articleId, Long authorOfAnnotationId) {
        this.id = id;
        this.pathOfFile = pathOfFile;
        this.annotation = annotation;
        this.articleId = articleId;
        this.authorOfAnnotationId = authorOfAnnotationId;
    }

    public String getPathOfFilel() {
        return pathOfFile;
    }

    public void setPathOfFile(String pathOfFile) {
        this.pathOfFile = pathOfFile;
    }

    public String getAnnotation() {
        return annotation;
    }

    public void setAnnotation(String annotation) {
        this.annotation = annotation;
    }

    public Long getArticleId() {
        return articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public Long getAuthorOfAnnotationId() {
        return authorOfAnnotationId;
    }

    public void setAuthorOfAnnotationId(Long authorOfAnnotationId) {
        this.authorOfAnnotationId = authorOfAnnotationId;
    }
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/ArticleDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import cz.cvut.fel.system.bo.Status;
import java.util.List;

/**
 *
 * @author Jirka
 */
public class ArticleDto extends AbstractDto {

    private String name;
    private Boolean priority;
    private Status status;
    private List<Long> annotationsIDs;
    private List<Long> authorsIDs;
    private Long correctorID;
    private List<Long> versions;

    public ArticleDto() {
    }

    public List<Long> getVersions() {
        return versions;
    }

    public void setVersions(List<Long> versions) {
        this.versions = versions;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean isPriority() {
        return priority;
    }

    public void setPriority(Boolean priority) {
        this.priority = priority;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public List<Long> getAnnotationsIDs() {
        return annotationsIDs;
    }

    public void setAnnotationsIDs(List<Long> annotationsIDs) {
        this.annotationsIDs = annotationsIDs;
    }

    public List<Long> getAuthorsIDs() {
        return authorsIDs;
    }

    public void setAuthorsIDs(List<Long> authorsIDs) {
        this.authorsIDs = authorsIDs;
    }

    public Long getCorrectorID() {
        return correctorID;
    }

    public void setCorrectorID(Long correctorID) {
        this.correctorID = correctorID;
    }
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/AuthorDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import java.util.List;

/**
 *
 * @author Jirka
 */
public class AuthorDto extends PersonAbstractDto {

    List<Long> articleIds;

    public AuthorDto() {
    }



    public List<Long> getArticleIds() {
        return articleIds;
    }

    public void setArticleIds(List<Long> articleIds) {
        this.articleIds = articleIds;
    }
    
    
    
    
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/CorrectorDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import java.util.List;

/**
 *
 * @author Jirka
 */
public class CorrectorDto extends PersonAbstractDto {

    List<Long> articleIds;
    String email;

    public CorrectorDto() {
        super();
    }

    public List<Long> getArticleIds() {
        return articleIds;
    }

    public void setArticleIds(List<Long> articleIds) {
        this.articleIds = articleIds;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/DtoFactory.java
/*
 * To change a template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import cz.cvut.fel.system.bo.Admin;
import cz.cvut.fel.system.bo.AdvisoryBoardMember;
import cz.cvut.fel.system.bo.Annotation;
import cz.cvut.fel.system.bo.Article;
import cz.cvut.fel.system.bo.Author;
import cz.cvut.fel.system.bo.Corrector;
import cz.cvut.fel.system.bo.User;
import cz.cvut.fel.system.bo.Version;
import cz.cvut.fel.system.helper.DtoTransformerHelper;
import cz.cvut.fel.system.helper.HibernateTools;

/**
 *
 * @author marcel
 */
public  class DtoFactory {

    public static AdminDto getDto(Admin a) {
        AdminDto dto = new AdminDto();
        dto.setId(a.getId());
        dto.setRole(a.getUserRole());

        dto.setUsername(a.getUsername());
        return dto;
    }

    public static AdvisoryBoardMemberDto getDto(AdvisoryBoardMember a) {
        AdvisoryBoardMemberDto dto = new AdvisoryBoardMemberDto();
        dto.setId(a.getId());
        dto.setFirstname(a.getFirstname());
        dto.setLastname(a.getLastname());
        dto.setRole(a.getUserRole());
        dto.setUsername(a.getUsername());
        return dto;
    }

    public static AnnotationDto getDto(Annotation a) {
        AnnotationDto dto = new AnnotationDto();
        dto.setAnnotation(a.getAnnotationText());
        dto.setArticleId(HibernateTools.getIdentifier(a.getArticle()));
        dto.setAuthorOfAnnotationId(HibernateTools.getIdentifier(a.getAuthorOfAnnotation()));
        dto.setId(a.getId());
        dto.setPathOfFile(a.getPathOfFile());
        return dto;
    }

    public static ArticleDto getDto(Article a) {
        ArticleDto dto = new ArticleDto();
        dto.setId(a.getId());
        dto.setAnnotationsIDs(DtoTransformerHelper.getIdentifiers(a.getAnnotations()));
        dto.setAuthorsIDs(DtoTransformerHelper.getIdentifiers(a.getAuthors()));
        dto.setCorrectorID(HibernateTools.getIdentifier(a.getCorrector()));
        dto.setName(a.getName());
        dto.setPriority(a.getPriority());
        dto.setStatus(a.getStatus());
        dto.setVersions(DtoTransformerHelper.getIdentifiers(a.getVersions()));
        return dto;
    }

    public static AuthorDto getDto(Author a) {
        AuthorDto dto = new AuthorDto();
        dto.setFirstname(a.getFirstname());
        dto.setLastname(a.getLastname());
        dto.setId(a.getId());
        dto.setRole(a.getUserRole());
        dto.setUsername(a.getUsername());
        dto.setArticleIds(DtoTransformerHelper.getIdentifiers(a.getArticles()));
        return dto;
    }

    public static CorrectorDto getDto(Corrector a) {
        CorrectorDto dto = new CorrectorDto();
        dto.setId(a.getId());
        dto.setRole(a.getUserRole());
        dto.setFirstname(a.getFirstname());
        dto.setLastname(a.getLastname());
        dto.setUsername(a.getUsername());
        dto.setArticleIds(DtoTransformerHelper.getIdentifiers(a.getArticles()));
        dto.setEmail(a.getEmail());

        return dto;
    }

    public static UserDto getDto(User a) {
        UserDto dto = new UserDto();
        dto.setId(a.getId());
        dto.setRole(a.getUserRole());
        dto.setUsername(a.getUsername());
        return dto;
    }

    public static VersionDto getDto(Version a) {
        VersionDto dto = new VersionDto();
        dto.setArticleID(HibernateTools.getIdentifier(a.getArticle()));
        dto.setDatetime(a.getDatetime());
        dto.setId(a.getId());
        dto.setPathOfFile(a.getPathOfFile());
        return dto;
    }
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/PersonAbstractDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

/**
 *
 * @author marcel
 */
public abstract class PersonAbstractDto extends UserDto{
    
    String firstname;
    String lastname;

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/UserDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import cz.cvut.fel.system.bo.Role;

/**
 *
 * @author Jirka
 */
public class UserDto extends AbstractDto {

    private String username;
    private Role role;

    public UserDto() {
    }

    public UserDto(Long id, String username) {
        this.id = id;
        this.username = username;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }
    
    
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/dto/VersionDto.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.dto;

import java.util.Date;

/**
 *
 * @author marcel
 */
public class VersionDto extends AbstractDto {

    private Long articleID;
    private Date datetime;
    private String pathOfFile;

    public VersionDto() {
    }

    public Long getArticleID() {
        return articleID;
    }

    public void setArticleID(Long articleIDs) {
        this.articleID = articleIDs;
    }

    public Date getDatetime() {
        return datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getPathOfFile() {
        return pathOfFile;
    }

    public void setPathOfFile(String PathOfFile) {
        this.pathOfFile = PathOfFile;
    }

    @Override
    public String toString() {
        return "VersionDto{" + "articleID=" + articleID + ", datetime=" + datetime + ", pathOfFile=" + pathOfFile + '}';
    }
    
    
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/bb/HelloBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.system.bb;

import java.util.Date;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author Jirka
 */
@ManagedBean//trida ale JSF anotace... aplikace proleze vsechny managed beany a vytvori objekty

public class HelloBean {
    
    protected String message = "beana test! Výpis z beany";
    protected String name;
    
    public String getMessage(){
        return message;
    }
    
    public void setMessage(String message){
        this.message = message;
    }
    public String getName(){
        return name;
    }
    public void setName(String name){
        this.name = name;
    }
    
    
        public String sayHello(){
            return "greetings.xtml";        
        }
    
    public String getDate(){
        return new Date().toString();
    }
    
    
}

SystemProPripravuClankuDoCasopisu/src/main/java/cz/cvut/fel/system/controller/FileUploadController.java
package cz.cvut.fel.system.controller;
 
import javax.faces.application.FacesMessage;  
import javax.faces.context.FacesContext;  
  
import org.primefaces.model.UploadedFile;  
  
/**
 *
 * @author Jirka
 */
public class FileUploadController {
    private UploadedFile file;  
  
    public UploadedFile getFile() {  
        return file;  
    }  
  
    public void setFile(UploadedFile file) {  
        this.file = file;  
    }  
  
    public void upload() {  
        if(file != null) {  
            FacesMessage msg = new FacesMessage("Succesful", file.getFileName() + " is uploaded.");  
            FacesContext.getCurrentInstance().addMessage(null, msg);  
        }  
    }  
}

SystemProPripravuClankuDoCasopisu/src/main/webapp/addArticleAnnotation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title><h:outputText value="#{msg['addArticleAnnotation']}" /></title>
    </h:head>
    <h:body>
        <ui:include src="/WEB-INF/include.xhtml" />

        <h1><h:outputText value="#{msg['addArticleAnnotation']}" /></h1>
        <div>#{msg['article']}: #{addArticleVersionBB.name}</div>
        <h:form>
            #{msg['annotationText']}:
            <br/>
            <h:inputTextarea rows="4" cols="50" value="#{addArticleAnnotationBB.annotationText}"></h:inputTextarea>
            <br/>

            <h:commandButton value="#{msg['addArticleAnnotation']}" action="#{addArticleAnnotationBB.addAnnotation(addArticleVersionBB.articleId)}">
                <f:param name="articleId" value="#{addArticleAnnotationBB.articleId}"/>
            </h:commandButton>
        </h:form>



    </h:body>
</html>

SystemProPripravuClankuDoCasopisu/src/main/webapp/addArticleVersion.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title><h:outputText value="#{msg['addArticleVersion']}" /></title>
    </h:head>
    <h:body>
        <ui:include src="/WEB-INF/include.xhtml" />

        <h1><h:outputText value="#{msg['addArticleVersion']}" /></h1>
        <div>#{msg['article']}: #{addArticleVersionBB.name}</div>
        <h:form enctype="multipart/form-data">

            <p:messages showDetail="true"/>  
            <p:fileUpload value="#{addArticleVersionBB.file}" mode="simple"/> 
            <br/><br/>

            <h:commandButton value="#{msg['create.article.add']}" action="#{addArticleVersionBB.addVersion(param.articleId)}" >
                <f:param name="articleId" value="#{param.articleId}"></f:param>
            </h:commandButton>
            <br/>
            <h:messages showDetail="true"/>
            <p:messages autoUpdate="true" />
        </h:form>



    </h:body>
</html>

SystemProPripravuClankuDoCasopisu/src/main/webapp/createArticle.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title><h:outputText value="#{msg['create.article.title']}" /></title>
    </h:head>
    <h:body>
        <ui:include src="/WEB-INF/include.xhtml" />
        
        <h1><h:outputText value="#{msg['create.article.title']}" /></h1>
        <h:form enctype="multipart/form-data">
            <h:outputText value="#{msg['create.article.name']}" /> <h:inputText value="#{articleBB.name}"/><br/>
            <h:outputText value="#{msg['create.article.priority']}" /> <h:selectBooleanCheckbox value="#{articleBB.priority}"/> <br/>

            <p:messages showDetail="true"/>  
            <p:fileUpload value="#{articleBB.file}" mode="simple"/> 
            <br/><br/>

            <h:commandButton value="#{msg['create.article.create']}" action="#{articleBB.saveArticle()}"/>
            <br/>
            <h:messages showDetail="true"/>
            <p:messages autoUpdate="true" />
        </h:form>



    </h:body>
</html>

SystemProPripravuClankuDoCasopisu/src/main/webapp/detailArticle.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
        <title>#{msg['article']}: #{articleDetailBB.name}</title>
    </h:head>
    <h:body>
        <ui:include src="/WEB-INF/include.xhtml" />
        <div class="articleDetailBody">
            <h1>#{articleDetailBB.name}</h1>
            <div class="authors">

                Authors: #{articleDetailBB.authors}
                <br/>
                <h:link value="Edit authors" outcome="/editAuthors">
                    <f:param name="articleId" value="#{articleDetailBB.articleId}">
                    </f:param>
                </h:link>  
                <br/>
                <br/>
            </div>
            <span class="message1">#{articleDetailBB.message}</span>
            <c:if test="${loginBB.role=='ROLE_CORRECTOR' and not(articleDetailBB.checked)}">
                <h:form>
                    <h:commandLink action="#{articleDetailBB.markAsCorrected}" value="#{msg['markAsCorrected']}" >
                        <f:param name="articleId" value="#{articleDetailBB.articleId}"/>
                    </h:commandLink>
                </h:form>
                <br/>
            </c:if>

            <div class="versions">
                #{msg['versions']}:
                <c:if test="#{articleDetailBB.versionDtos.rowAvailable}">
                    <h:dataTable style="border:1px gray solid;" value="#{articleDetailBB.versionDtos}" var="item" >
                        <h:column>
                            <h:outputLink value="#{request.contextPath}/resources/files/#{item.pathOfFile}">
                                #{item.datetime.toString()}
                            </h:outputLink>
                        </h:column>
                        <h:column>
                            <c:if test="${loginBB.role=='ROLE_AUTHOR'}">
                                <h:form>
                                    <h:commandButton value="Delete version" action="#{articleDetailBB.deleteVersion}" >
                                        <f:param name="articleId" value="#{articleDetailBB.articleId}"/>
                                    </h:commandButton>
                                </h:form>
                            </c:if>
                        </h:column>
                    </h:dataTable>
                </c:if>
                <c:if test="#{not articleDetailBB.versionDtos.rowAvailable}">
                    <br/>
                    #{msg['noVersions']}
                    <br/>

                </c:if>

                <c:if test="${loginBB.role=='ROLE_AUTHOR'}">
                    <h:link outcome="/addArticleVersion" value="#{msg['addArticleVersion']}">
                        <f:param name="articleId" value="#{articleDetailBB.articleId}"></f:param>
                    </h:link>
                </c:if>
            </div>
            <br/>
            <div class="annotatios">
                #{msg['annotations']}:<br/>
                <c:if test="${articleDetailBB.annotationDtos != null and articleDetailBB.annotationDtos.size() > 0}">
                    <h:dataTable style="border:1px gray solid;" value="#{articleDetailBB.annotationDtos}" var="item" >
                        <h:column>
                            #{articleDetailBB.getAuthorNameById(item.authorOfAnnotationId)}
                        </h:column>
                        <h:column>
                            #{item.annotation.toString()}
                        </h:column>
                    </h:dataTable>
                </c:if>
                <c:if test="${not (articleDetailBB.annotationDtos != null and articleDetailBB.annotationDtos.size() > 0)}">
                    #{msg['noAnnotations']}
                </c:if>

                <c:if test="${loginBB.role=='ROLE_AUTHOR' or loginBB.role=='ROLE_BOARD_MEMBER' or loginBB.role=='ROLE_CORRECTOR'}">
                    <br/>
                    <h:link outcome="/addArticleAnnotation" value="#{msg['addArticleAnnotation']}">
                        <f:param name="articleId" value="#{articleDetailBB.articleId}"></f:param>
                    </h:link>
                </c:if>
            </div>



        </div>
    </h:body>
</html>

SystemProPripravuClankuDoCasopisu/src/main/webapp/editAuthors.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:head>
        <title>#{msg['article']}: #{articleDetailBB.name}</title>
    </h:head>
    <h:body>
        <ui:include src="/WEB-INF/include.xhtml" />
         <h1><h:outputText value="Edit Authors" /></h1>
         <div>#{msg['article']}: #{editAuthorsBB.name}</div>

        <div class="editAuthorsBody">

            <div class="authorsTable">
                #{msg['authors']}:
                <c:if test="#{editAuthorsBB.authorDtos.rowAvailable}">
                    <h:dataTable style="border:1px gray solid;" value="#{editAuthorsBB.authorDtos}" var="item" >
                        <h:column>
                            #{item.firstname} #{item.lastname}
                        </h:column>
                        <h:column>
                            <c:if test="${loginBB.role=='ROLE_AUTHOR' or loginBB.role=='ROLE_BOARD_MEMBER'}">
                                <h:form id="delete">
                                    <h:commandButton value="Remove author" action="#{editAuthorsBB.deleteAuthor}" >
                                        <f:param name="articleId" value="#{editAuthorsBB.articleId}"/>
                                    </h:commandButton>
                                </h:form>
                            </c:if>
                        </h:column>
                    </h:dataTable>
                </c:if>
                <c:if test="#{not articleDetailBB.versionDtos.rowAvailable}">
                    <br/>
                    #{msg['noAuthors']}
                    <br/>

                </c:if>

                <c:if test="${loginBB.role=='ROLE_AUTHOR' or loginBB.role=='ROLE_BOARD_MEMBER'}">
                    <h:form id="add">
                        <h:selectOneMenu id="allAuthors"  required="true"  value="#{editAuthorsBB.selectedAuthorId}"> 
                            <f:selectItem itemValue="none" itemLabel="Choose Author" />
                            <f:selectItems value="#{editAuthorsBB.allAuthors}"/>
                        </h:selectOneMenu>
                        <h:commandButton value="Add author" action="#{editAuthorsBB.submit}" >
                            <f:param name="articleId" value="#{editAuthorsBB.articleId}"/>
                        </h:commandButton>


                    </h:form>
                </c:if>



            </div>
            <br/>
            <h:link value="Back to article" outcome="/detailArticle">
                <f:param name="articleId" value="#{editAuthorsBB.articleId}">
                </f:param>
            </h:link>

        </div>

    </h:body>
</html>

SystemProPripravuClankuDoCasopisu/src/main/webapp/greetings.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        
        Hello <h:outputText value="${helloBean.name}"/>
        Today is <h:outputText value="${helloBean.date}"/>
    
            
            
        
    </h:body>
</html>

SystemProPripravuClankuDoCasopisu/src/main/webapp/success.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title><h:outputText value="#{msg['create.article.title']}" /></title>
    </h:head>
    <h:body>
        <ui:include src="/WEB-INF/include.xhtml" />
        
        <h1><h:outputText value="#{param.message}" /></h1>
    </h:body>
</html>